# Generated by Django 5.2.12 on 2026-04-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busiwebapp', '0004_order_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='image',
        ),
        migrations.AddField(
            model_name='shoes',
            name='image_back',
            field=models.ImageField(blank=True, default='shoes/placeholder.jpg', null=True, upload_to='shoes/', verbose_name='Back Image'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='image_front',
            field=models.ImageField(default='shoes/placeholder.jpg', upload_to='shoes/', verbose_name='Front Image'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='image_left',
            field=models.ImageField(blank=True, default='shoes/placeholder.jpg', null=True, upload_to='shoes/', verbose_name='Left Side Image'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='image_right',
            field=models.ImageField(blank=True, default='shoes/placeholder.jpg', null=True, upload_to='shoes/', verbose_name='Right Side Image'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='old_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Old Price (for discount display)'),
        ),
    ]
