# Generated by Django 5.2.12 on 2026-04-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busiwebapp', '0005_remove_shoes_image_shoes_image_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apparels',
            name='image',
        ),
        migrations.RemoveField(
            model_name='toys',
            name='image',
        ),
        migrations.AddField(
            model_name='apparels',
            name='image_back',
            field=models.ImageField(blank=True, default='apparels/placeholder.jpg', null=True, upload_to='apparels/', verbose_name='Back Image'),
        ),
        migrations.AddField(
            model_name='apparels',
            name='image_front',
            field=models.ImageField(default='apparels/placeholder.jpg', upload_to='apparels/', verbose_name='Front Image'),
        ),
        migrations.AddField(
            model_name='apparels',
            name='image_left',
            field=models.ImageField(blank=True, default='apparels/placeholder.jpg', null=True, upload_to='apparels/', verbose_name='Left Side Image'),
        ),
        migrations.AddField(
            model_name='apparels',
            name='image_right',
            field=models.ImageField(blank=True, default='apparels/placeholder.jpg', null=True, upload_to='apparels/', verbose_name='Right Side Image'),
        ),
        migrations.AddField(
            model_name='apparels',
            name='old_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Old Price (for discount display)'),
        ),
        migrations.AddField(
            model_name='toys',
            name='image_back',
            field=models.ImageField(blank=True, default='toys/placeholder.jpg', null=True, upload_to='toys/', verbose_name='Back Image'),
        ),
        migrations.AddField(
            model_name='toys',
            name='image_front',
            field=models.ImageField(default='toys/placeholder.jpg', upload_to='toys/', verbose_name='Front Image'),
        ),
        migrations.AddField(
            model_name='toys',
            name='image_left',
            field=models.ImageField(blank=True, default='toys/placeholder.jpg', null=True, upload_to='toys/', verbose_name='Left Side Image'),
        ),
        migrations.AddField(
            model_name='toys',
            name='image_right',
            field=models.ImageField(blank=True, default='toys/placeholder.jpg', null=True, upload_to='toys/', verbose_name='Right Side Image'),
        ),
        migrations.AddField(
            model_name='toys',
            name='old_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Old Price (for discount display)'),
        ),
    ]
